services:
  - type: web
    name: printbroker
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: printbroker-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: printbroker-redis
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/v1/health
    autoDeploy: true

  - type: staticSite
    name: printbroker-frontend
    buildCommand: npm install && npm run build:client
    staticPublishPath: dist/public
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE_URL
        value: https://printbroker.onrender.com

databases:
  - name: printbroker-db
    databaseName: printbroker
    user: printbroker
    plan: free

services:
  - type: redis
    name: printbroker-redis
    plan: free
    maxmemoryPolicy: noeviction 